package com.forgeci.application.github;
import com.forgeci.application.auth.AuthException; import com.forgeci.application.security.FieldEncryptionService; import com.forgeci.application.organization.OrganizationService; import com.forgeci.domain.organization.GitHubConnection; import com.forgeci.domain.organization.GitHubConnectionStatus; import com.forgeci.domain.organization.Organization; import com.forgeci.infrastructure.organization.GitHubConnectionRepository; import com.forgeci.infrastructure.organization.OrganizationRepository; import com.forgeci.infrastructure.user.UserRepository; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.Instant; import java.util.*; import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class GitHubConnectionService{
 private final GitHubClient github; private final GitHubConnectionRepository connections; private final UserRepository users; private final OrganizationRepository organizations; private final OrganizationService organizationService; private final FieldEncryptionService encryption; private final byte[] stateSecret;
 public GitHubConnectionService(GitHubClient g,GitHubConnectionRepository c,UserRepository u,OrganizationRepository o,OrganizationService os,FieldEncryptionService e,@Value("${forgeci.github.state-secret}")String s){github=g;connections=c;users=u;organizations=o;organizationService=os;encryption=e;stateSecret=s.getBytes(StandardCharsets.UTF_8);if(stateSecret.length<32)throw new IllegalArgumentException("GitHub state secret must be at least 32 characters");}
 public String authorizeUrl(UUID userId,UUID organizationId){if(!organizationService.canManage(userId,organizationId))throw new AuthException("FORBIDDEN","Organization administrator access required");String payload=userId+":"+organizationId+":"+Instant.now().getEpochSecond()+":"+UUID.randomUUID();return github.authorizationUrl(payload+":"+sign(payload));}
 @Transactional public void callback(String state,String code)throws Exception{String[] p=state.split(":");if(p.length!=5)throw new AuthException("INVALID_OAUTH_STATE","Invalid GitHub OAuth state");UUID userId=UUID.fromString(p[0]);UUID orgId=UUID.fromString(p[1]);long issued=Long.parseLong(p[2]);if(Instant.now().getEpochSecond()-issued>600||!MessageDigest.isEqual(sign(String.join(":",Arrays.copyOf(p,4))).getBytes(StandardCharsets.UTF_8),p[4].getBytes(StandardCharsets.UTF_8)))throw new AuthException("INVALID_OAUTH_STATE","Invalid GitHub OAuth state");if(!organizationService.canManage(userId,orgId))throw new AuthException("FORBIDDEN","Organization administrator access required");var token=github.exchangeCode(code).accessToken();var gh=github.currentUser(token);var user=users.findById(userId).orElseThrow(()->new AuthException("USER_NOT_FOUND","User not found"));Organization org=organizations.findById(orgId).orElseThrow(()->new AuthException("ORGANIZATION_NOT_FOUND","Organization not found"));var cipher=encryption.encrypt(token);var existing=connections.findByOrganizationIdAndExternalAccountId(orgId,gh.id());if(existing.isPresent()){existing.get().updateToken(cipher,null);connections.save(existing.get());}else connections.save(new GitHubConnection(org,gh.id(),gh.login(),cipher,null));}
 @Transactional public void disconnect(UUID userId,UUID organizationId){if(!organizationService.canManage(userId,organizationId))throw new AuthException("FORBIDDEN","Organization administrator access required");connections.findAllByOrganizationId(organizationId).stream().filter(c->c.getStatus()==GitHubConnectionStatus.ACTIVE).forEach(c->{c.disconnect();connections.save(c);});}
 public String token(UUID userId,UUID organizationId){if(!organizationService.isMember(userId,organizationId))throw new AuthException("FORBIDDEN","Organization membership required");return decryptActiveToken(organizationId);}
 public String webhookToken(UUID organizationId){return decryptActiveToken(organizationId);}
 private String decryptActiveToken(UUID organizationId){var c=connections.findFirstByOrganizationIdAndStatus(organizationId,GitHubConnectionStatus.ACTIVE).orElseThrow(()->new AuthException("GITHUB_NOT_CONNECTED","GitHub is not connected"));return encryption.decrypt(c.getEncryptedAccessToken());}
 private String sign(String p){try{var m=Mac.getInstance("HmacSHA256");m.init(new SecretKeySpec(stateSecret,"HmacSHA256"));return Base64.getUrlEncoder().withoutPadding().encodeToString(m.doFinal(p.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
